import {Dish} from './Dish';


export const DISHES: Dish[] = [
  {
    name: 'Barszcz',
    cusine: 'polska',
    categories: ["danie główne", "zupa", "na ciepło", "mięsne"],
    price: '$3.99',
    ingredients: ['bulion mięsny', 'buraki', 'czosnek', 'uszka', 'grzyby'],
    max_orders: 10,
    image_src: 'https://drive.google.com/uc?export=view&id=1TK6SXzJDOhs85kiTNMGrRbz6dG0kPEm-',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1TK6SXzJDOhs85kiTNMGrRbz6dG0kPEm-',
    'https://drive.google.com/uc?export=view&id=1UmTacoApnf6T9ma4K3c95DNvkKAklI6c',
    'https://drive.google.com/uc?export=view&id=1XJSIIqa-KIkoV4dol048ABzEUg_-JvhH'],
    rate: -1,
    rate_counter: 0,
    description: ''
  },
  {
    name: 'Burger',
    cusine: 'amerykańska',
    categories: ["danie główne", "przystawka", "na ciepło", "mięsne"],
    price: '$4.99',
    ingredients: ['mięso', 'bułka pszenna', 'sałata', 'ser', 'sos'],
    max_orders: 200,
    image_src: 'https://drive.google.com/uc?export=view&id=1SK6JcZY3aSTgac1vCMClGdT9bsLvros3',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1SK6JcZY3aSTgac1vCMClGdT9bsLvros3',
    'https://drive.google.com/uc?export=view&id=10xVDb-1AzrbjvIgdFIe-F0X9yhxM5nEe',
    'https://drive.google.com/uc?export=view&id=12NGyeGXPEgjmQznOHalWhxWE2XLbbnRo'],
    rate: 4,
    rate_counter:1,
    description: ''
  },
  {
    name: 'Pierogi',
    cusine: 'polska',
    categories: ["danie główne","na ciepło", "wegetariański"],
    price: '$7.99',
    ingredients: ["mąka", "mleko", "ziemniaki", "jajka", "ser biały"],
    max_orders: 2137,
    image_src: 'https://drive.google.com/uc?export=view&id=1adImkAUQmR6Vzg9qR9wPx6tTGbIOd0q-',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1adImkAUQmR6Vzg9qR9wPx6tTGbIOd0q-',
    'https://drive.google.com/uc?export=view&id=1nqPbGUdWhtm6LBYeXV-sT-aoVLwoldUF',
    'https://drive.google.com/uc?export=view&id=1LvVeTrdcAAJI0Y9fFS1MP7Ad1BShzDp3'],
    rate: 5,
    rate_counter: 10,
    description: ''
  },
  {
    name: 'Gołąbki',
    cusine: 'polska',
    categories: ["danie główne","na ciepło", "mięsne"],
    price: '$10.99',
    ingredients: ["kapusta", "mięso", "ryż", "ziemniaki"],
    max_orders: 69,
    image_src: 'https://drive.google.com/uc?export=view&id=1rPtYxzr2GkReNymut_TrqG-SobpST8fJ',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1rPtYxzr2GkReNymut_TrqG-SobpST8fJ',
    'https://drive.google.com/uc?export=view&id=1x_SN_hOLzhyTS_McI4DXCfNjMjn1ENnD',
    'https://drive.google.com/uc?export=view&id=1Y2vdH1vY2jOK9wS2wCfeK-Okzx0GDYGF'],
    rate: 2,
    rate_counter: 1,
    description: ''
  },
  {
    name: 'Kurczak po chińsku',
    cusine: 'chińska',
    categories: ["danie główne","na ciepło", "mięsne", "przystawka"],
    price: '$20.99',
    ingredients: ["makaron", "kurczak", "warzywa"],
    max_orders: 10,
    image_src: 'https://drive.google.com/uc?export=view&id=18qBuvsVMuKnJBsL_LGqQSjdrf0Hl8cju',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=18qBuvsVMuKnJBsL_LGqQSjdrf0Hl8cju',
    'https://drive.google.com/uc?export=view&id=1mVHa4sFjaDMBHEBkEwnU3Nwuo_JTRn6q',
    'https://drive.google.com/uc?export=view&id=12NZbF8GOvr6QJP8ACmSWmhbDSnx8-DiD'],
    rate: 5,
    rate_counter: 2,
    description: ''
  },
  {
    name: 'Naleśniki',
    cusine: 'międzynarodowa',
    categories: ["danie główne","na ciepło", "wegańskie"],
    price: '$7.99',
    ingredients: ["mąka", "mleko sojowe", "olej", "sól", "owoce"],
    max_orders: 100,
    image_src: 'https://drive.google.com/uc?export=view&id=19-UsTkn4fYj036SBo-lNOf8YJf1xkMzP',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=19-UsTkn4fYj036SBo-lNOf8YJf1xkMzP',
    'https://drive.google.com/uc?export=view&id=1cglqejXPphQVbPreBzpbYB_byhjjqsMy',
    'https://drive.google.com/uc?export=view&id=1EexqiiePeEGqZ3gpTPAdOU_3QPeg1-DB'],
    rate: 3,
    rate_counter:2,
    description: ''
  },
  {
    name: 'Pizza',
    cusine: 'międzynarodowa',
    categories: ["danie główne","na ciepło"],
    price: '$19.99',
    ingredients: ["mąka", "warzywa", "mięso"],
    max_orders: 123,
    image_src: 'https://drive.google.com/uc?export=view&id=1vy6ky1LDBSa_4cqQS7n88fFRKeFaQo2v',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1vy6ky1LDBSa_4cqQS7n88fFRKeFaQo2v',
    'https://drive.google.com/uc?export=view&id=1Ac7UlcEEgKo-sYmoY1SgwSclirC2nz4-',
    'https://drive.google.com/uc?export=view&id=1Howqz5KzZsf976bE2c4iO5AxaW2kG47S'],
    rate: 4.5,
    rate_counter: 2,
    description: ''
  },
  {
    name: 'Ramen',
    cusine: 'chińska',
    categories: ["danie główne","na ciepło", "zupa"],
    price: '$29.99',
    ingredients: ["bulion", "makaron", "mięso", "jajka", "warzywa"],
    max_orders: 50,
    image_src: 'https://drive.google.com/uc?export=view&id=1jsJn8Znux2a6QSGBRYXk3a0fNp6uELmV',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1jsJn8Znux2a6QSGBRYXk3a0fNp6uELmV',
    'https://drive.google.com/uc?export=view&id=1dPz78z9-MUl-GiYCA_dDWXEhbE33HvSP',
    'https://drive.google.com/uc?export=view&id=1BvzRBC8Ufbxi-CCtxo9EJ1SNXVG8ZSWM'],
    rate: 3,
    rate_counter: 1,
    description: ''
  },
  {
    name: 'Sernik',
    cusine: 'międzynarodowa',
    categories: ["deser"],
    price: '$9.99',
    ingredients: ["twaróg", "mąka", "jajka", "cukier trzcinowy"],
    max_orders: 60,
    image_src: 'https://drive.google.com/uc?export=view&id=11-G0fJU99qVZ_oSqqa1AnrXPwoNCzJAF',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=11-G0fJU99qVZ_oSqqa1AnrXPwoNCzJAF',
    'https://drive.google.com/uc?export=view&id=1CJh5fwat-9u2E-OrsbnFtqbrIvLm-WDt',
    'https://drive.google.com/uc?export=view&id=1NNWd1b6VqUatjPHinEuMjezdOp3otA8W'],
    rate: 1,
    rate_counter: 1,
    description: ''
  },
  {
    name: 'Spaghetti',
    cusine: 'włoska',
    categories: ["danie główne","na ciepło", "mięsne"],
    price: '$15.99',
    ingredients: ["makaron", "sos", "warzywa"],
    max_orders: 21,
    image_src: 'https://drive.google.com/uc?export=view&id=1nPDMcXhaxRpr9i7zo26LOzVeZeSAZwDI',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1nPDMcXhaxRpr9i7zo26LOzVeZeSAZwDI',
    'https://drive.google.com/uc?export=view&id=1RpuxCvLs3npEZNqnRuJ6aSv9_nXeiQwq',
    'https://drive.google.com/uc?export=view&id=15NZ3wyWw3NNb6bU55H-BY4tCLHDRaiOt'],
    rate: 5,
    rate_counter: 9,
    description: ''
  },
  {
    name: 'Sushi',
    cusine: "japońska",
    categories: ["danie główne","na zimno"],
    price: '$21.99',
    ingredients: ["ryż", "ryba", "wodorosty nori", "owoce morza"],
    max_orders: 3,
    image_src: 'https://drive.google.com/uc?export=view&id=17YkmZx1AbvywifmfSa79JDn9S14PsqOH',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=17YkmZx1AbvywifmfSa79JDn9S14PsqOH',
    'https://drive.google.com/uc?export=view&id=12ysUVP440ue7AXSdQhpH7Z8j9e0ac1z4',
    'https://drive.google.com/uc?export=view&id=1bnDf-Z7tHOPgFuwcEKiCyNck_KJhwErx'],
    rate: 3,
    rate_counter: 10,
    description: ''
  },
  {
    name: 'Tiramisu',
    cusine: "międzynarodowa",
    categories: ["deser"],
    price: '$10.99',
    ingredients: ["kawa", "likier amaretto", "jajka", "mąka", "cukier", "mascarpone", "kakao"],
    max_orders: 30,
    image_src: 'https://drive.google.com/uc?export=view&id=1sCg3Ewp3ANbrrhDnra8FldwYLAUfi1af',
    image_src_optional: ['https://drive.google.com/uc?export=view&id=1sCg3Ewp3ANbrrhDnra8FldwYLAUfi1af',
    'https://drive.google.com/uc?export=view&id=1H5P6W5GMJ454l8QENOoNAKv2oWzuT5Z1',
    'https://drive.google.com/uc?export=view&id=1BaqqdqotWxQnkgHN_xZLvG7gW8wtqEie'],
    rate: 4,
    rate_counter: 1,
    description: ''
  },

]
